### ISSUE TITLE
Create 2BNB Berets

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#24]
So that we can destroy in style! 

An example: https://goo.gl/images/fVx1n3

Apparently that guy is part of the Nord Brigade.

**Comment by Qaiten** [comment]
Put a .paa & .png file which I retextured from another Beret mod. But I don't have the no-how to actually put the .paa to a beret in order to use it in-game. 

Location in GDrive; [https://drive.google.com/drive/folders/1vbKlsoWH5hibNwwJUkYbaRElJDPwpSCy](url)

Couldn't find the insignia that the photo used on the Beret so I used our own.

**Comment by UrekD** [comment]
@Qaiten Fix da berret cyka
