### ISSUE TITLE
AI have "Hold Spacebar to Revive" menu item

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#29]
**Arma 3 Version:** `1.90` (stable)
**2BNB Extras Version:** `1.5.0` (stable)
**2BNB Modpack Version:** `1.0.6`

**Description:**
AI have a scroll menu saying "Hold Spacebar to Revive". This should probably not be enabled when ACE medical works.

**Steps to reproduce:**
- Move to an injured/unconscious AI unit
- Look at the unit and scroll to open the scroll menu

**Where did the issue occur?**
- 2BNB Server

**Comment by UrekD** [comment]
Indeed, thats PIR which won't br getting ace compatibility. Since AI is on basic medical due to the fuckers refusing to bandage since they rather bleed out, what would be your proposed solution (state of the AI) that they would be considered revived ( on basic their pressure and pulse is not simulated I belive aswell as blood, parts only have low medium and high damage modifier.

**Comment by UrekD** [comment]
Speaking of this maybe the code can be modified so this works on player and he's down until he is considered stable by ace standarts.

**Comment by Saborknight** [comment]
The point here is more to get rid of the addAction, it won't be wantef

**Comment by UrekD** [comment]
Yeah I get the point, but then we can't revive AI at all like :
- civs
- friendly
- hvt
Without zeus heal.

**Comment by UrekD** [comment]
"Removed standard treatment system." In the new update, haven't been on today will check and push tomorrow!
