### ISSUE TITLE
x Has died sound notification

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#93]
The notification sound when a person dies plays for all the players not just zeus.

**Comment by Saborknight** [comment]
Funny because I'm just using the function that Achilles uses. However, I think the execution of the function happens on each person's computer due to the function not actually doing any checks to see if the person is actually a Zeus. I think that's what's up.

This should be a simple fix where we just get a list of Zeuses and then only send to them here: https://github.com/2bnb/2bnb-extras/blob/master/addons/core/XEH_postInit.sqf#L57

This is stupid though, because that function should be doing this check, not us... Goddamn Achilles

**Comment by Saborknight** [comment]
Better yet, all Achilles does (as seen here: https://github.com/ArmaAchilles/Achilles/blob/master/%40AresModAchillesExpansion/addons/functions_f_ares/common/fn_ShowZeusMessage.sqf) is concatenate all parameters into a single string if there are more than one, and then it just calls the function `bis_fnc_showCuratorFeedbackMessage`. So we can just create our own function for this that does an additional check of whether or not the person is Zeus, and then executes the above.

**Comment by UrekD** [comment]
Well my suggestion is either push a fix by Sunday or remove it until fix cuz its annoying on the ground.

**Comment by Saborknight** [comment]
This is in reference to the features added in #92

**Comment by UrekD** [comment]
Should be simple tho just has innterface check?

**Comment by Saborknight** [comment]
It is simple, but `hasInterface` is the incorrect method to use, since that just checks if a player is a player.

**Comment by Saborknight** [comment]
Finished testing with success!
