### ISSUE TITLE
2BNB Filtered arsenal no JIP

### ISSUE THREAD

**Issue by UrekD** [2bnb/2bnb-extras#94]
Filter for the arsenal is aplied on the mission start but dosen't work for people who join after/reconnect.

Possible fix "ace_arsenal_fnc_initBox"?? 

https://ace3mod.com/wiki/framework/arsenal-framework.html

**Comment by Saborknight** [comment]
I'm thinking maybe there's something going on with us calling it every time a user connects? Because as far as I remember it's a global function, so shouldn't be called multiple times.

**Comment by UrekD** [comment]
Are we I don't see any joip in code isn't that handled by ace? did ya check why only  box was filtered last op tho?

**Comment by Saborknight** [comment]
Well yeah, my point is exactly that, ACE is already executing on [JIP](https://github.com/acemod/ACE3/blob/ed1488edbab4d576549558fcecc513b4d0e0dd75/addons/arsenal/functions/fnc_initBox.sqf#L31). But we're also doing it because every time a client loads in, they init the box on their client... but that makes a call to the framework, with then kickstarts the initbox to execute AGAIN. I think that's where the issue is, so I believe just doing a check "hasArsenal" should be enough to stop this, or perhaps add our own variable to the object saying "don't update me!" or something.
Looking into the code now, we'll see what I come up with.

**Comment by Saborknight** [comment]
I'm now thinking that there may be some issue where the CBA setting related to the arsenal is not being fetched reliably, perhaps a similar thing to what is happening to the Climate settings not being applied consistently... Needs further experimentation

**Comment by Saborknight** [comment]
This is assuming that my earlier fix in https://github.com/Saborknight/2bnb-framework/commit/a6709b4a5b5c0f65b7ba9f4a51432b630feca01b didn't end up fixing it. Still haven't been able to test that.

**Comment by Saborknight** [comment]
The 3DEN module has been put back into using initBox instead of the attributes, since the attributes thing wasn't working: b32e6f5af8a6dee586b36982c133c72fc3b34b54

**Comment by Saborknight** [comment]
In the latest update, this seems to have been fixed! Tested untampered with multiple load fresh load ins, and also with the Zeus module applying a different filter, and then relogging a few times and it behaved as expected.
